### ISSUE TITLE
AddTableLines throws System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/PdfTextReader#44]
CRITICAL ERROR: Unhandled Exception
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source, Func`2 selector)
   at PdfTextReader.Base.BlockSet`1.GetH() in C:\Users\fcatae\Desktop\PdfTextReader\src\PdfTextReader\Base\BlockSet.cs:line 38
   at PdfTextReader.PDFCore.AddTableLines.IsBelowBody(IBlock line, BlockPage page) in C:\Users\fcatae\Desktop\PdfTextReader\src\PdfTextReader\PDFCore\AddTableLines.cs:line 74
   at PdfTextReader.PDFCore.AddTableLines.Process(BlockPage page) in C:\Users\fcatae\Desktop\PdfTextReader\src\PdfTextReader\PDFCore\AddTableLines.cs:line 49

**Comment by fcatae** [comment]
Impact: DO1_2010_02_24
