### ISSUE TITLE
BreakInlineElements throws System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/PdfTextReader#45]
CRITICAL ERROR: Unhandled Exception
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source, Func`2 selector)
   at PdfTextReader.Base.BlockSet`1.GetX() in C:\Users\fcatae\Desktop\PdfTextReader\src\PdfTextReader\Base\BlockSet.cs:line 37
   at PdfTextReader.PDFCore.BreakInlineElements.OverlapContains(IBlock a, IBlock b) in C:\Users\fcatae\Desktop\PdfTextReader\src\PdfTextReader\PDFCore\BreakInlineElements.cs:line 155

**Comment by fcatae** [comment]
Impact: DO1_2010_12_20

**Comment by fcatae** [comment]
This is an Unhandled Exception, and it leads to a crash. The correct approach is to raise `PdfReaderExceptions` instead. Since this is an expected behavior (block is a single line), then we will change it to a warning.
```
PdfReaderException.Warning("size == 0 | size == -1 (block is indivisible?)");
```
