### ISSUE TITLE
ERRO CRÍTICO - Documentos DO1_2016_01_11 e DO1_2016_01_12 não processados!

### ISSUE THREAD

**Issue by lcarli** [DXBrazil/PdfTextReader#46]
CRITICAL ERROR: Unhandled Exception
PdfTextReader.Base.PdfReaderException: size == -1
   at PdfTextReader.Base.PdfReaderException.AlwaysThrow(String message, String source, String sourceMethod) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\Base\PdfReaderException.cs:line 76

**Comment by lcarli** [comment]
+ 1 DOCUMENTO - > DO1_2016_01_14

**Comment by fcatae** [comment]
@lcarli copia mais algumas linhas da excecao por favor.

**Comment by fcatae** [comment]
Nao sei exatamente o que era, mas está corrigido no último build.

**Comment by lcarli** [comment]
Continua com o erro.

WARNING: Process: checkZeroW failed (C:\Users\luhumenh\OneDrive\MS\Projects\CasaCivil\PDFs\Sample\2016_01_14/DO1_2016_01_14.pdf, Page 10)
WARNING: BreakPage: BreakColumnsLight:checkOverlap (C:\Users\luhumenh\OneDrive\MS\Projects\CasaCivil\PDFs\Sample\2016_01_14/DO1_2016_01_14.pdf, Page 37)
PdfTextReader.Base.PdfReaderException: size == -1 (C:\Users\luhumenh\OneDrive\MS\Projects\CasaCivil\PDFs\Sample\2016_01_14/DO1_2016_01_14.pdf, Page 37)
   at PdfTextReader.Base.PdfReaderException.AlwaysThrow(String message, String source, String sourceMethod) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\Base\PdfReaderException.cs:line 94
   at PdfTextReader.PDFCore.BreakColumnsLight.BreakPage(BlockPage page) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\PDFCore\BreakColumnsLight.cs:line 124
   at PdfTextReader.PDFCore.BreakColumnsLight.Process(BlockPage page) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\PDFCore\BreakColumnsLight.cs:line 13
   at PdfTextReader.Execution.PipelinePage.ParseBlock[T]() in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\Execution\PipelinePage.cs:line 114
   at PdfTextReader.ProgramValidator2016.<>c.<GetTextLines>b__3_0(PipelineInputPdfPage page) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\ProgramValidator2016.cs:line 66
   at PdfTextReader.Execution.PipelineInputPdf.ProtectCall(Action`1 callback, PipelineInputPdfPage pdfPage) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\Execution\PipelineInputPdf.cs:line 261
File DO1_2016_01_14: End

**Comment by lcarli** [comment]
@fcatae , Apesar de mostrar o erro crítico, ele gerou os XMLs. Vou deixar aberto apenas para que você veja o stack de erro.

Pode fechar quando quiser!

**Comment by fcatae** [comment]
obrigado
