### ISSUE TITLE
DO1_2016_01_18 - PdfTextReader.Base.PdfReaderException: image == null 

### ISSUE THREAD

**Issue by lcarli** [DXBrazil/PdfTextReader#53]
CRITICAL ERROR: Unhandled Exception
PdfTextReader.Base.PdfReaderException: image == null (C:\Users\luhumenh\OneDrive\MS\Projects\CasaCivil\PDFs\Sample\2016_01_18/DO1_2016_01_18.pdf, Page 1)
   at PdfTextReader.Base.PdfReaderException.AlwaysThrow(String message, String source, String sourceMethod) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\Base\PdfReaderException.cs:line 94
   at PdfTextReader.PDFCore.RemoveHeaderImage.Process(BlockPage page) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\PDFCore\RemoveHeaderImage.cs:line 50
   at PdfTextReader.Execution.PipelinePage.ParseBlock[T]() in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\Execution\PipelinePage.cs:line 114
   at PdfTextReader.ExamplesWork.BreakColumn(String basename) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\ExamplesWork.cs:line 99
   at PdfTextReader.ExamplesWork.PrintAllSteps(String name, String inputfolder, String outputfolder) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\ExamplesWork.cs:line 30
   at PdfTextReader.ProgramValidator2016.Process(String basename, String inputfolder, String outputfolder) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\PdfTextReader\ProgramValidator2016.cs:line 28
   at Validator.Process2016.Run(File file, String outputname) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\Validator\Process2016.cs:line 21
   at Validator.Runner.Run(IRunner runner, File file, String outputname) in C:\Users\luhumenh\Documents\GitHub\PdfTextReader\src\Validator\Runner.cs:line 38

File DO1_2016_01_18: End with FAILURES

**Comment by fcatae** [comment]
Existem imagens acima do cabeçalho - alterando a lógica para capturar tudo
